# Generated by Django 3.2.3 on 2022-08-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='valor',
            field=models.FloatField(null=True, verbose_name='Receita mensal'),
        ),
    ]
