# Generated by Django 3.2.3 on 2022-08-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_receita_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='data_pub',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='data_pub',
        ),
        migrations.AddField(
            model_name='despesa',
            name='valor',
            field=models.FloatField(null=True, verbose_name='Despesa mensal'),
        ),
    ]
