# Generated by Django 3.2.3 on 2022-08-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_auto_20220821_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanco',
            name='text',
        ),
    ]
