# Generated by Django 3.2.3 on 2022-08-21 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_remove_balanco_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanco',
            name='dsp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.despesa'),
        ),
        migrations.AddField(
            model_name='balanco',
            name='rct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financas.receita'),
        ),
    ]
