# Generated by Django 3.2.3 on 2022-08-27 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_auto_20220821_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanco',
            name='dsp',
        ),
        migrations.RemoveField(
            model_name='balanco',
            name='rct',
        ),
        migrations.AddField(
            model_name='balanco',
            name='despesas',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='financas.despesa'),
        ),
        migrations.AddField(
            model_name='balanco',
            name='receitas',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='financas.receita'),
        ),
        migrations.AddField(
            model_name='balanco',
            name='text',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
