# Generated by Django 3.2.3 on 2022-08-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0006_auto_20220827_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanco',
            name='receitas',
        ),
        migrations.AddField(
            model_name='balanco',
            name='receitas',
            field=models.ManyToManyField(to='financas.Receita'),
        ),
    ]
