# Generated by Django 3.2.3 on 2022-08-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0007_auto_20220827_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanco',
            name='despesas',
        ),
        migrations.AddField(
            model_name='balanco',
            name='despesas',
            field=models.ManyToManyField(to='financas.Despesa'),
        ),
    ]
