# Generated by Django 3.2.3 on 2022-08-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0008_auto_20220827_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanco',
            name='despesas',
        ),
        migrations.RemoveField(
            model_name='balanco',
            name='receitas',
        ),
    ]
