# Generated by Django 3.2.3 on 2022-08-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0009_auto_20220827_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanco',
            name='despesas',
            field=models.ManyToManyField(to='financas.Despesa'),
        ),
        migrations.AddField(
            model_name='balanco',
            name='receitas',
            field=models.ManyToManyField(to='financas.Receita'),
        ),
    ]
