# Generated by Django 3.2.3 on 2022-08-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0015_auto_20220828_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanco',
            name='despesas',
        ),
        migrations.AddField(
            model_name='balanco',
            name='despesas',
            field=models.ManyToManyField(to='financas.Despesa'),
        ),
        migrations.RemoveField(
            model_name='balanco',
            name='receitas',
        ),
        migrations.AddField(
            model_name='balanco',
            name='receitas',
            field=models.ManyToManyField(to='financas.Receita'),
        ),
    ]
