# Generated by Django 3.2.3 on 2022-08-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0017_auto_20220831_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='balanco',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='balanco',
        ),
        migrations.AddField(
            model_name='balanco',
            name='despesas',
            field=models.ManyToManyField(to='financas.Despesa'),
        ),
        migrations.AddField(
            model_name='balanco',
            name='receitas',
            field=models.ManyToManyField(to='financas.Receita'),
        ),
    ]
