# Generated by Django 3.2.3 on 2022-08-31 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0018_auto_20220831_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanco',
            name='despesas',
        ),
        migrations.RemoveField(
            model_name='balanco',
            name='receitas',
        ),
        migrations.AddField(
            model_name='despesa',
            name='balanco',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='financas.balanco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='balanco',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='financas.balanco'),
            preserve_default=False,
        ),
    ]
