# Generated by Django 3.2.3 on 2022-08-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0019_auto_20220831_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.IntegerField(null=True, verbose_name='Despesa mensal'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.IntegerField(null=True, verbose_name='Receita mensal'),
        ),
    ]
