# Generated by Django 3.2.3 on 2022-08-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0021_remove_receita_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='valor',
            field=models.IntegerField(null=True, verbose_name='Receita mensal'),
        ),
    ]
