# Generated by Django 3.2.3 on 2022-08-31 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0023_calculo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculo',
        ),
    ]
