# Generated by Django 3.2.3 on 2022-09-01 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0024_delete_calculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancoCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balanco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.balanco')),
                ('despesas', models.ManyToManyField(to='financas.Despesa')),
                ('receitas', models.ManyToManyField(to='financas.Receita')),
            ],
        ),
    ]
