# Generated by Django 3.2.3 on 2022-09-01 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0027_auto_20220901_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='balanco',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='balanco',
        ),
    ]
