# Generated by Django 3.2.3 on 2022-09-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0028_auto_20220901_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanco',
            name='despesas',
            field=models.ManyToManyField(to='financas.Despesa'),
        ),
        migrations.AddField(
            model_name='balanco',
            name='receitas',
            field=models.ManyToManyField(to='financas.Receita'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.FloatField(null=True, verbose_name='Despesa mensal'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.FloatField(null=True, verbose_name='Receita mensal'),
        ),
    ]
