# Generated by Django 3.2.3 on 2022-09-01 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0030_auto_20220901_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanco',
            name='balanconome',
        ),
        migrations.RemoveField(
            model_name='balanco',
            name='despesas',
        ),
        migrations.RemoveField(
            model_name='balanco',
            name='receitas',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='balanconome',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='balanconome',
        ),
        migrations.AddField(
            model_name='despesa',
            name='balanco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.balanco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='balanco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.balanco'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BalancoNome',
        ),
    ]
