# Generated by Django 3.2.3 on 2022-09-01 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0031_auto_20220901_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancoNome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='balanco',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='balanco',
        ),
        migrations.AddField(
            model_name='balanco',
            name='despesas',
            field=models.ManyToManyField(to='financas.Despesa'),
        ),
        migrations.AddField(
            model_name='balanco',
            name='receitas',
            field=models.ManyToManyField(to='financas.Receita'),
        ),
        migrations.AddField(
            model_name='balanco',
            name='balanconome',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='financas.balanconome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesa',
            name='balanconome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financas.balanconome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='balanconome',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='financas.balanconome'),
            preserve_default=False,
        ),
    ]
