# Generated by Django 3.2.3 on 2022-09-01 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0032_auto_20220901_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='balanconome',
        ),
    ]
