# Generated by Django 3.2.3 on 2022-09-01 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0033_remove_receita_balanconome'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='balanconome',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='financas.balanconome'),
            preserve_default=False,
        ),
    ]
