# Generated by Django 3.2.3 on 2022-09-01 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0034_receita_balanconome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BalancoNome',
            new_name='Titulo',
        ),
    ]
