# Generated by Django 3.2.3 on 2022-09-01 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0035_rename_balanconome_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balanco',
            old_name='balanconome',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='despesa',
            old_name='balanconome',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='balanconome',
            new_name='titulo',
        ),
    ]
