# Generated by Django 3.2.3 on 2022-09-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0036_auto_20220901_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25)),
                ('senha', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'usuário',
            },
        ),
    ]
