# Generated by Django 3.2.3 on 2022-09-01 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0037_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='login',
            new_name='nomeuser',
        ),
    ]
